[package]
name = "auth-server"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.7.4", features = ["serde", "v4"] }
auth-common = { path = "../common" }
lazy_static = "1.3.0"
failure = "0.1.5"
time = "0.1.42"
bcrypt = "0.5.0"
rouille = "3.0.0"
postgres = "0.16.0-rc.2"
r2d2_postgres = "0.15.0-rc.1"
r2d2 = "0.8.5"
