[package]
name = "server"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.40"
uuid = { version = "0.7.4", features = ["v4"] }
auth-common = { path = "../common" }
rusqlite = { version = "0.20.0", features = ["bundled"] }
parking_lot = "0.9.0"
lazy_static = "1.3.0"
failure = "0.1.5"
