version: "3.7"
networks:
  main:
services:
  web:
    image: auth-server
    networks:
      - main
    depends_on:
      - db
    ports:
      - "19253:19253"

  db:
    image: postgres:11
    networks:
      - main
    command: postgres -c 'max_connections=16'
    environment:
      POSTGRES_PASSWORD: supersecret1337
