version: "3.1"
services:
  auth:
    image: auth-server:latest
    ports:
      - "19253:19253"
    environment:
      DB_PROVIDER: db
      CACHE_PROVIDER: cache
  db:
    image: postgres:11-alpine
    command: postgres -c 'max_connections=17'
    volumes:
      - "/my/own/datadir:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: supersecret1337
  cache:
    image: redis:5-alpine
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]
