version: "3.1"
services:
  auth:
    image: auth-server
    ports:
      - "19253:19253"

  db:
    image: postgres:11
    command: postgres -c 'max_connections=17'
    environment:
      POSTGRES_PASSWORD: supersecret1337
