version: "3.1"
services:
  auth:
    image: auth-server:latest
    ports:
      - "19253:19253"
    environment:
      DB_PROVIDER: db
  db:
    image: postgres:11
    command: postgres -c 'max_connections=17'
    volumes:
      - "/my/own/datadir:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: supersecret1337
  cache:
    image: redis:5
