[package]
name = "authc"
version = "1.0.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.9.19", default-features = false, features = ["rustls-tls"] }
uuid = { version = "0.7.4", features = ["serde", "v4"] }
auth-common = { git = "https://gitlab.com/veloren/auth.git" }
serde = { version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
