[package]
name = "authc"
version = "1.0.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.9.24", default-features = false, features = ["rustls-tls"] }
uuid = { version = "0.7.4", features = ["serde", "v4"] }
auth-common = { path = "../common" }
serde_json = "1.0.40"
sha3 = "0.8.2"
hex = "0.3.2"
