[package]
name = "authc"
version = "1.0.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.0", default-features = false, features = ["rustls-tls", "blocking"] }
uuid = { version = "0.7.4", features = ["serde", "v4"] }
auth-common = { path = "../common" }
serde_json = "1.0.40"
hex = "0.3.2"
fxhash = "0.2.1"
rust-argon2 = "0.6.1"
